### ISSUE TITLE
Unable to load the application

### ISSUE THREAD

**Issue by suryatejaambati** [vsquared/ecg#1]
When I add the ECG graph code, it stops my application and showing that "Unfortunately you application got stopped"

I used the code as you  uploaded here

**Comment by vsquared** [comment]
Runs fine here.  Please describe your hardware setup:  type of boards and type of smartphone.  How are you making the bluetooth connection?  Which IDE are you using; NetBeans or Eclipse?  Why are you "adding" the ECG graph code; it is an integral part of the source code and does not need to be "added"?

**Comment by suryatejaambati** [comment]
Hi, I am using Arduino Mini (ATMega328 Processor) with HC-05 Bluetooth. And I am using a Samsung Core Duoss smartphone GT-I8262(4.1.2 Jeally bean). 
Regarding the bluetooth I successfully got connected and displaying the text on the screen.
I am using Intellij Idea IDE.
I took code which is similar to yours from the below link "https://github.com/plastygrove/BlueSerial" where it doesn't have graphview module. So I am using your graphview code in the above application.
Please let me know, is there any thing wrong i am doing so far!!

By the thanks for your replay

**Comment by vsquared** [comment]
You are using a totally different hardware setup than what was used in the video project, as well as different source code.  The only thing in common is GraphView, which was never intended to be used as a stand alone module; it was intended to be included in the source code that I posted.  Therefore, it is not surprising that you have an error.  That’s not to say that it can’t be made to work.  GraphView is relatively simple, and more than likely you do not have it hooked up correctly.  Please go back and look at the remainder of the posted source code to see how it was incorporated, and then see if you can duplicate that.  Alternatively, you could write your own GraphView (using the posted code as a template) and incorporate it into the source code that you are using.  I’m afraid that trouble shooting will have to be done on your end.  Thank you for your interest.
